# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWE4ODU5YjA2MWY3NTI5NDE5ZTBiMmMyMjUwYTg0MmNmZjFiMjAzZmJiYjUxMzhiNzU5ZTYyMjM0N2I0ZWVlYTcxYWZjMWUzMzJlZWUxNmQ3NzBlMjM2YzAzMDlkMmNiZWExOTI3OTExMWJlYjk4MGY1MjQ2MzczMjk4NDUzMjg=
