# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MGUyMDM3ZDA1NjMxOGM0MzAyNzZlMDJhMWQ1ZTcyYWFmNjM2ZGM4M2UzOGI0ZGEzMzY0M2I0YTBiOTAzNThkZjdiYjI0ZTdjMTUwNTVlNWRmMjk4YmFlNzE1MmJlNmI2NmU1MjM1YTkxZDc0YmQzNzU3MTM0YmYwNTdmMzY2NzY=
